### ISSUE TITLE
QG4 System Team checks

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/bpdm#101]
### Please keep this issue open until QG4 is concluded!

Product Name: BPDM
Product Owner: Tim Rybak 
Dev SPOC: @nicoprow 
Helm Chart Version Pool: ~`4.3.0`~ → `4.3.1`
Helm Chart Version Gate: ~`3.3.0`~ →  `3.3.1`
App Version: ~`3.2.1`~  →  `3.2.2`
QG4 Approval: yes/no

##### TRG 1.01
https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-1
- [x] an appropriate `README.md` file
###### TRG 1.02
https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-2
- [x] an appropriate `INSTALL.md`
###### TRG 1.03
https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-3
- [x] an appropriate `CHANGELOG.md`
  - [x] the versioning itself follows [semantic versioning](https://semver.org/)
##### TRG 2.01
https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-1
- [x] default branch is named `main`
##### TRG 2.03
https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-3
- [x] `/docs` directory
- [x] must contain detailed product related documentation for the Tractus-X product
- [x] `/charts` directory
- [x] must contain the Helm chart for the Tractus-X product IF available
- [x] `AUTHORS.md` file (optional)
- [x] #130
- [x] #129
- [x] `DEPENDENCIES` file(s)
- [x] run Dash tool to compare #115
- [x] `LICENSE` file
- [x] `NOTICE.md` file
- [x] `SECURITY.md` file #107

##### TRG 2.04
https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-4
- [x] a Leading product repository
- [x] repository name must be _productname_ without prefix or suffix
- [x] should contain the release
- [x] references/urls to the product's other repositories
- [x] might contain product helm chart
- [x] README.md: contains the urls for the backend and frontend applications #109
- [x] Links to Repository
- [x] Does it reference all other repositories?
- [x] Does it contain the Product Helm chart?
##### TRG 2.05
https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-5
- [x] `.tractusx` metafile is present in the root of the repository #108 
- [x] file has a proper format
##### TRG 3.02
https://eclipse-tractusx.github.io/docs/release/trg-3/trg-3-2
- [x] if data persistence is needed in Kubernetes the use of PersistentVolume and PersistentVolumeClaim resource
##### TRG 4.01
https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-1
- [x] All images must be tagged following [semantic versioning](https://semver.org/)
- [x] container is labeled correctly additionally to the latest tag
##### TRG 4.02
https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-2
- [x] must add a section to your top level `README.md` file, that contains information about the used base image
- [x] Java, Kotlin, ... if JVM based language use base image from [Eclipse Temurin](https://hub.docker.com/_/eclipse-temurin)
##### TRG 4.03
https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-3
- [x] image has `USER` command to specify a non-root user to run the container https://github.com/eclipse-tractusx/bpdm/issues/110
- [x] `deployment.yaml` has `runAsUser` and `allowPrivilegeEscalation: false` properly set
##### TRG 4.05
https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-5
- [x] released image must be present on `GitHub Package registry` or `Dockerhub`
##### TRG 5.01
https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-01
- [x] Helm chart must be released
- [x] appropriate semantic versioning for `version` and `appVersion` has to be used in `Chart.yaml`
- [x] must not contain any environment specific `values-xyz.yaml`
- [x] `values.yaml` file must contain proper default values/placeholders
- [x] No hostname provided for ingress
- [x] Ingress is disabled
- [x] No references to any secret engine service (e.g.: Hashicorp Vault)
- [x] Dependencies should be prefixed with the nameOverride and/or fullnameOverride properties
- [x] Image tag is set to the `Chart.yaml` `appVersion` property #112 
- [x] must be deployable to any environment without overwriting default values with a simple helm install command
- [x] dependencies have to be declared in Chart.yaml NOT requirements.yml
- [x] recommended use GitHub [Chart Releaser Action](https://github.com/helm/chart-releaser-action)
##### TRG 5.02
https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-02
- [x] Helm chart location inside Git repository in `/charts` directory
- [x] chart file structure #113
``` markdown
charts/ 
    chartNameA/
      Chart.yaml
      ... 
    chartNameB/
      Chart.yaml
      ...
AUTHORS.md 
DEPENDENCIES.md 
LICENCE 
README.md 
```
- [x] each file must contain the [Apache 2.0 Licence](https://github.com/catenax-ng/foss-example/blob/main/general/LICENSE)
- [x] latest tag is not used in helm chart be default
##### TRG 5.04
https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-04
- [x] CPU and memory limits and requests are properly set
##### TRG 5.06
https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-06
- [x] every startup configuration aspect of your application must be configurable through the Helm chart (ingress class, tls, labels, annotations, database, secrets, persistence, env variables)
##### TRG 5.07
https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-07
- [x] if dependencies are present in the `Chart.yaml` they are properly configured
##### TRG 5.08
https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-08
- [x] a product has a single deployable helm chart that contains all components (backend, frontend, etc.)
- [x] name of the Chart should be just the product-name without prefix or suffix
- [x] values file should contain all available variables (even from subcharts) with default values and comments about what they do
- [x] helm install command should successfully install the chart to any supported Kubernetes version cluster (without overwriting default values)
- [x] helm test runs without errors

#### Testing
- [x] installed and running on pre-prod without errors

#### Hints

#114

#### Information Sharing

**Comment by FaGru3n** [comment]
Hi bpdm Team! 👋🏼 

could you please provide us some more information, that we can check? 

``` markdown
Product Name:   BPDM
Product Owner:  
Dev SPOC:  
Helm Chart Version Pool:  `4.3.0`
Helm Chart Version Gate:  `3.3.0`
App Version:  
QG4 Approval: yes/no
``` 
Thanks in advance.

**Comment by FaGru3n** [comment]
Hi @nicoprow,

thanks for your feedback.

to avoid confusion on my side, you created tags within repo for each product componet? 
So this leads to following git-tags?
Helm Chart Version Pool: `4.3.0` --> https://github.com/eclipse-tractusx/bpdm/tree/bpdm-pool-4.3.0
Helm Chart Version Gate: `3.3.0` --> https://github.com/eclipse-tractusx/bpdm/tree/bpdm-gate-3.3.0
App Version: 3.2.1

**Comment by FaGru3n** [comment]
Hi @nicoprow,

created you some issue to checkout
#115
#113
#112
#110
#109
#108
#107
and a little hint
#114

**Comment by FaGru3n** [comment]
Hi @nicoprow,

seems only one task is open could maybe generate a new release and update the versions?
#112

**Comment by nicoprow** [comment]
Due to changes towards charts and app the patch versions are now increased:

Helm Chart Version Pool: 4.3.1
Helm Chart Version Gate: 3.3.1
App Version: 3.2.2

**Comment by FaGru3n** [comment]
> Due to changes towards charts and app the patch versions are now increased:
> 
> Helm Chart Version Pool: 4.3.1 Helm Chart Version Gate: 3.3.1 App Version: 3.2.2

Pre-Prod charts seems running

**Comment by FaGru3n** [comment]
updated chart reference and checked on pre-prod
