### ISSUE TITLE
CleaningServiceDummy: Setup new Module

### ISSUE THREAD

**Issue by nicoprow** [eclipse-tractusx/bpdm#421]
We need a new module that should act as a place holder for the cleaning service provider. With the new orchestration architecture our BridgeDummy becomes deprecated and needs to be replaced with a more elaborate approach.

### Tasks
 - [x] New pom module and Spring Boot application in the BPDM project called CleaningServiceDummy
 - [x]  Module has a basic structure derived from the bpdm-common module
 - [x] Deployment files for the BPDM Chart
 - [x] Workflow to publish the CleaningServiceDummy Dockerfile
 - [x] Include the CleaningServiceDummy in Trivy

**Comment by gerlitmcoding** [comment]
Also add to deployment charts

**Comment by rainer-exxcellent** [comment]
According to the diagram depicted in #377 the CleaningServiceDummy has access to the Pool API and the forthcomming OrchestrationLayer

**Comment by nicoprow** [comment]
I added tasks for creating necessars workflows
