### ISSUE TITLE
Orchestrator: Setup new Module

### ISSUE THREAD

**Issue by nicoprow** [eclipse-tractusx/bpdm#422]
With the new orchestration architecture we need to have a new application in the BPDM project that manages the processing of cleaning requests for business partner data.

### Tasks
 - [x] New pom module and Spring Boot application in the BPDM project called Orchestrator
 - [x] Module has a basic structure derived from the bpdm-common module
 - [x] Deployment files for the BPDM Chart
 - [x] Workflow to publish the CleaningServiceDummy Dockerfile
 - [x] Include the CleaningServiceDummy in Trivy

Dependencies
#377 
#424

**Comment by gerlitmcoding** [comment]
Also add to deployment charts
