### ISSUE TITLE
CleaningServiceDummy: Create Dummy Cleaning Result

### ISSUE THREAD

**Issue by nicoprow** [eclipse-tractusx/bpdm#433]
Lacking a service provider who can perform cleaning of business partner records we need a simple dummy logic mocking the generic cleaning process while still providing usable cleaning results for the next steps in the orchestration.

One of the biggest tasks in this issue is to create legal entity, site and address representations from the given generic business partner data. The service logic behaviour is dependent on the postal address type:

For creating a legal entity representation:

- Overtake the legal entity specific fields in the generic business partner
- Create the legal address as described in creating address representation
- If the generic business partner has a BPNL assign the legal entity the same BPNL
- If the generic business partner has no BPNL assign a new BPN request id as the legal entity's BPNL

For creating a site representation:
- Only create a site representation if the generic business business partner has a BPNS or if the postal address is either LegalAndSiteMainAddress or SiteMainAddress
- Overtake the name generic business partner
- Create the site main address as described in creating address representation
- If the generic business partner has a BPNS assign the site the same BPNS
- If the generic business partner has no BPNS assign a new BPN request id as the site's BPNS

For creating an address representation: 
- Overtake the name, identifiers and postal address of the generic business partner
- If the generic business partner has a BPNA assign the address the same BPNA
- If the generic business partner has no BPNA assign a new BPN request id as the addresse's BPNA

Legal Address, Site Main Address and Address Partner may share a newly BPN request id based on the address type of the generic business partner:
- LegalAndSiteMainAddress: Same BPN request id for all three addresses
- LegalAddress: Same BPN request id for Legal Address and Address Partner
- SiteMainAddress: Same BPN request id for Site Main Address and Address Partner
- AdditionalAddress: All addresses have different BPN request ids

The field value  for 'hasChanged' of the L/S/A partners is always true.

The BPN request identifier is a random UUID.

###Tasks
- [x] Request new cleaning tasks for step "GenericCleaning" from Orchestrator (see #458 )
- [x] Create Legal Entity, Site and Address representations from the given generic business partner data
- [x] Create BPN request identifiers where missing
- [x] Post dummy cleaning results to Orchestrator for step "GenericCleaning" (see #458)
- [x] Create configurable scheduling for performing these on regular time interval

Dependencies:
#388 
#392

**Comment by nicoprow** [comment]
Cleaning Service Dummy can be dumbed down a little bit more: Just don't access the Pool to get actual data and always convert the current generic business partner to its L/S/A representations.

**Comment by nicoprow** [comment]
I simplified the logic for creating dummy cleaning results a bit. Now, legal entities and address representations are always created. The Pool needs to understand this logic and update/create business partners accordingly.

**Comment by martinfkaeser** [comment]
How are the identifiers (and states) from the generic BP split between legalEntity and legalEntity.legalAddress?
If all identifiers were copied to both of them, the Pool might reject them if the identifier type is only valid for either LE or A.

**Comment by fabiodmota** [comment]
So, I have a service that runs every x minutes with scheduling. 
The first call fetches a task from the orchestrator for cleaning.

Doubt: We need to validate whether this is a legal entity address or site, but how can we know to map from generic to the corresponding LSA type? We have the fields bpnA, bpnS, and bpnL, but these may not be filled out. 
We also have the AddressType field that has some nomenclatures (for example, LegalAndSiteMainAddress); can this field also be empty? And in that case, do we assume one by default? What means do we have to validate what type this generic is? 

@nicoprow @martinfkaeser @rainer-exxcellent  i think you are the ones most in knowledge to answer this

**Comment by nicoprow** [comment]
> So, I have a service that runs every x minutes with scheduling. The first call fetches a task from the orchestrator for cleaning.
> 
> Doubt: We need to validate whether this is a legal entity address or site, but how can we know to map from generic to the corresponding LSA type? We have the fields bpnA, bpnS, and bpnL, but these may not be filled out. We also have the AddressType ( comment on top from nico '**The service logic behaviour is dependent on the postal address type'** ) field that has some nomenclatures (for example, LegalAndSiteMainAddress); can this field also be empty? And in that case, do we assume one by default? What means do we have to validate what type this generic is?
> 
> @nicoprow @martinfkaeser @rainer-exxcellent i think you are the ones most in knowledge to answer this

To elaborate the logic in the issue description: Independent of which BPNs or address type is given, we always create a legal entity with legal address and a logistic address from given generic business partner data.

The BPNs and address type only influence what is being written in the BPN reference fields and whether also a site will be created.

**Comment by fabiodmota** [comment]
After clearing the logic part here is a diagram from mermaid of the logic implemented

```mermaid
graph TD;
    ScheduleProcess(Schedule Process: Scheduled Task) --> Step1(Step 1: Fetch and Reserve Cleaning Request)
    Step1 -->|cleaningRequest| Step2(Step 2: Generate Dummy Cleaning Results)
    
    Step2 -->|For Each reservedTask| CreateAddress(Create Address Representation)
    CreateAddress -->|addressPartner| CheckBpnA1{Does it have BpnA?}
    
    CheckBpnA1 -->|Yes| UseExistingBpnA1(Use Existing BpnA)
    CheckBpnA1 -->|No| GenerateBpnA1(Generate New BpnA)
    
    UseExistingBpnA1 -->|Existing BpnA| CheckLegalAddressType{Is Address Type Legal or LegalAndSiteMain?}
    GenerateBpnA1 -->|Generated BpnA| CheckLegalAddressType
    
    CheckLegalAddressType -->|Yes| UseBpnAForLegalAddress(Use BpnA for Legal Address)
    CheckLegalAddressType -->|No| GenerateBpnAForLegalAddress(Generate New BpnA for Legal Address)
    
    UseBpnAForLegalAddress -->|bpnAForLegalAddress| CreateLegalEntity(Create Legal Entity Representation)
    GenerateBpnAForLegalAddress -->|Generated BpnAForLegalAddress| CreateLegalEntity
    
    CreateLegalEntity -->|legalEntityDto| CheckBpnL{Does it have BpnL?}
    
    CheckBpnL -->|Yes| UseBpnL(Use Existing BpnL)
    CheckBpnL -->|No| GenerateBpnL(Generate New BpnL)
    
    UseBpnL -->|bpnLReference| CheckSiteAddressTypeBpns{ SiteMainAddress or LegalAndSiteMainAddress or bpns }
    GenerateBpnL -->|Generated BpnL| CheckSiteAddressTypeBpns{ SiteMainAddress or LegalAndSiteMainAddress or bpns }
    
    CheckSiteAddressTypeBpns -->|One condition is true| CheckSiteAddressType{ SiteMainAddress or LegalAndSiteMainAddress }
    
    CheckSiteAddressType -->|SiteMainAddress or LegalAndSiteMainAddress| UseBpnAForSiteAddress(Use BpnA for Site Address)
    CheckSiteAddressType -->| Neither is true | GenerateBpnAForSite(Generate New BpnA for Site)
    GenerateBpnAForSite --> UseBpnAForSiteAddress(Use BpnA for Site Address)
    CheckSiteAddressTypeBpns -->|Other| GroupBpnLAndA
    
    UseBpnAForSiteAddress -->|bpnAForSiteAddress| CreateSiteRepresentation(Create Site Representation)

    
    CreateSiteRepresentation -->|siteDto| CheckBpnS{Does it have BpnS?}
    
    CheckBpnS -->|Yes| UseBpnS(Use Existing BpnS)
    CheckBpnS -->|No| GenerateBpnS(Generate New BpnS)

    
    GroupBpnLAndA(Group Addres and LegalEntity)--> |Add Addres and LegalEntity to Results| Finalize( Group Results)
    
    
    UseBpnS -->|bpnSReference| GroupAllBpn(Group Addres, LegalEntity and Site)
    GenerateBpnS -->|Generated BpnS| GroupAllBpn
    
    GroupAllBpn -->|Add Addres, LegalEntity and Site to Results| Finalize( Group Results)
    
    Finalize --> | Step 3 | Step3(Send Result back to Orchestrator)
```

**Comment by fabiodmota** [comment]
PR merged we can close the issue @nicoprow
