### ISSUE TITLE
CleaningServiceDummy: Service and Setup Helmcharts

### ISSUE THREAD

**Issue by fabiodmota** [eclipse-tractusx/bpdm#453]
## Create Helm Charts Structure for CleaningService Module

We need to create a Helm chart structure for the new module, **CleaningService**. 
This Helm chart will define the deployment configurations, services, and other Kubernetes resources required for the **CleaningService** module.

### Acceptance Criteria:

- [x] A new Helm chart for **CleaningService** is created.
- [x] The chart should be compatible with our current Kubernetes setup.

### Tasks:

- [x] Create the base structure for the **CleaningService** Helm chart.
- [x] Define necessary Kubernetes resources (e.g., Deployment, Service, ConfigMap, etc.).
- [x] Test the Helm chart in a dev environment.
