### ISSUE TITLE
Orchestrator API: Cleaning Steps Endpoints

### ISSUE THREAD

**Issue by nicoprow** [eclipse-tractusx/bpdm#458]
The BPDM Orchestrator application needs endpoints in which cleaning services can integrate against. The idea here is to provide cleaning services a way to reserve cleaning tasks from the orchestrator, perform the actual cleaning asynchronously and then post the cleaning result back to the orchestrator.

For this, the orchestrator should have two cleaning steps endpoints:
1. Task Reservation: With this endpoint the requestor can reserve a number of cleaning tasks for a given cleaning step. The endpoint should return the next number of cleaning tasks together with the business partner data in cleaning.
2. Task Results: With this endpoint the requestor can post cleaning result for previously reserved tasks for a given cleaning step. The endpoint should accept an array of results for cleaning tickets by task identifier.

### Tasks
- [x] Create endpoint definition for task reservation in orchestrator api module
- [x] Create endpoint definition for task results in orchestrator api module
- [x] Implement endpoint definitions in orchestrator module by returning dummy data

[OpenApi Proposal](https://raw.githubusercontent.com/eclipse-tractusx/bpdm/docs/api/generic-input/docs/api/orchestrator-proposal.yaml) and the [Redoc Rendering](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/eclipse-tractusx/bpdm/docs/api/generic-input/docs/api/orchestrator-proposal.yaml)

**Comment by nicoprow** [comment]
I set the type of the legal entity and site address fields to addressPartner. This way the cleaning service can specify the full legal and site main addresses including bpn-reference and identifiers. I also renamed the address fields to legal address and site main address respectively.
