### ISSUE TITLE
Orchestrator: Service and Setup Helmcharts

### ISSUE THREAD

**Issue by fabiodmota** [eclipse-tractusx/bpdm#461]
## Create Helm Charts Structure for Orchestrator Module

We need to create a Helm chart structure for the new module, **Orchestrator **. 
This Helm chart will define the deployment configurations, services, and other Kubernetes resources required for the **Orchestrator** module.

### Acceptance Criteria:

- [x] A new Helm chart for **Orchestrator** is created.
- [x] The chart should be compatible with our current Kubernetes setup.

### Tasks:

- [x] Create the base structure for the **Orchestrator** Helm chart.
- [x] Define necessary Kubernetes resources (e.g., Deployment, Service, ConfigMap, etc.).
- [x] Test the Helm chart in a dev environment.

**Comment by fabiodmota** [comment]
Added new workflow for Orchestrator on https://github.com/eclipse-tractusx/bpdm/pull/474

**Comment by fabiodmota** [comment]
After  clearing the logic part here is a diagram from mermaid of the logic implemented

graph TD;
    ScheduleProcess(Schedule Process: Scheduled Task) --> Step1(Step 1: Fetch and Reserve Cleaning Request)
    Step1 -->|cleaningRequest| Step2(Step 2: Generate Dummy Cleaning Results)
    
    Step2 -->|For Each reservedTask| CreateAddress(Create Address Representation)
    CreateAddress -->|addressPartner| CheckBpnA1{Does it have BpnA?}
    
    CheckBpnA1 -->|Yes| UseExistingBpnA1(Use Existing BpnA)
    CheckBpnA1 -->|No| GenerateBpnA1(Generate New BpnA)
    
    UseExistingBpnA1 -->|Existing BpnA| CheckLegalAddressType{Is Address Type Legal or LegalAndSiteMain?}
    GenerateBpnA1 -->|Generated BpnA| CheckLegalAddressType
    
    CheckLegalAddressType -->|Yes| UseBpnAForLegalAddress(Use BpnA for Legal Address)
    CheckLegalAddressType -->|No| GenerateBpnAForLegalAddress(Generate New BpnA for Legal Address)
    
    UseBpnAForLegalAddress -->|bpnAForLegalAddress| CreateLegalEntity(Create Legal Entity Representation)
    GenerateBpnAForLegalAddress -->|Generated BpnAForLegalAddress| CreateLegalEntity
    
    CreateLegalEntity -->|legalEntityDto| CheckBpnL{Does it have BpnL?}
    
    CheckBpnL -->|Yes| UseBpnL(Use Existing BpnL)
    CheckBpnL -->|No| GenerateBpnL(Generate New BpnL)
    
    UseBpnL -->|bpnLReference| CheckSiteAddressTypeBpns{ SiteMainAddress or LegalAndSiteMainAddress or bpns }
    GenerateBpnL -->|Generated BpnL| CheckSiteAddressTypeBpns{ SiteMainAddress or LegalAndSiteMainAddress or bpns }
    
    CheckSiteAddressTypeBpns -->|One condition is true| CheckSiteAddressType{ SiteMainAddress or LegalAndSiteMainAddress }
    
    CheckSiteAddressType -->|SiteMainAddress or LegalAndSiteMainAddress| UseBpnAForSiteAddress(Use BpnA for Site Address)
    CheckSiteAddressType -->| Neither is true | GenerateBpnAForSite(Generate New BpnA for Site)
    GenerateBpnAForSite --> UseBpnAForSiteAddress(Use BpnA for Site Address)
    CheckSiteAddressTypeBpns -->|Other| GroupBpnLAndA
    
    UseBpnAForSiteAddress -->|bpnAForSiteAddress| CreateSiteRepresentation(Create Site Representation)

    
    CreateSiteRepresentation -->|siteDto| CheckBpnS{Does it have BpnS?}
    
    CheckBpnS -->|Yes| UseBpnS(Use Existing BpnS)
    CheckBpnS -->|No| GenerateBpnS(Generate New BpnS)

    
    GroupBpnLAndA(Group Addres and LegalEntity)--> |Add Addres and LegalEntity to Results| Finalize( Group Results)
    
    
    UseBpnS -->|bpnSReference| GroupAllBpn(Group Addres, LegalEntity and Site)
    GenerateBpnS -->|Generated BpnS| GroupAllBpn
    
    GroupAllBpn -->|Add Addres, LegalEntity and Site to Results| Finalize( Group Results)
    
    Finalize --> | Step 3 | Step3(Send Result back to Orchestrator)
