### ISSUE TITLE
Pool-API: Create administrative Level 1 endpoint

### ISSUE THREAD

**Issue by nicoprow** [eclipse-tractusx/bpdm#499]
Currently, in our data model the postal addresses contain a field for setting the administrative level 1 value. We expect here an ISO norm region code to be entered. For this, we created earlier metadata endpoints in the Pool which have the path "api/catena/regions". For a user it is confusing to have two different terminologies for the same concept, on time being called administrative level 1 and at another place called region. 

Therefore we should align the naming by introducing a new Pool Metadata endpoint and deprecating the old ones.

### Tasks
- [x] Add Metadata GET Endpoint "api/catena/administrative-areas-level1" (POST is no longer needed)
- [x] Connect the new GET endpoint with the existing service logic and region DTOs
- [x] Mark the region endpoints as deprecated

**Comment by nicoprow** [comment]
We should rename regions in the new endpoint with administrative level 1. 
Also:
regionCode -> code 
regionName -> name
