### ISSUE TITLE
Docs: Update EDC collections for new endpoints

### ISSUE THREAD

**Issue by nicoprow** [eclipse-tractusx/bpdm#509]
With the introduction of the generic business partner endpoints the setup postman collection for the EDC as well as the EDC test postman collection need to be updated.

### Tasks
- [x] Add generic business partner endpoint asset to EDC Setup postman collection
- [x] Add generic business partner endpoint to the EDC test postman collection
- [x] Add administrative areas level 1 endpoint to the EDC postman collection
