### ISSUE TITLE
Gate: Add business partner type 'Generic' to Changelog and Sharing State 

### ISSUE THREAD

**Issue by nicoprow** [eclipse-tractusx/bpdm#519]
Currently sharing state entries and changelog entries can be have a business partner type of either legal entity, site or address. With the introduction of generic business partners we should introduce a new business partner type 'Generic' for these entries. 

### Tasks 
- [ ] Set business partner type 'Generic' in a changelog entry for generic business partner
- [ ] Set business partner type 'Generic' in a sharing state for a generic business partner
- [ ] Make changelog entries filterable by Generic business partner type
- [ ] Make sharing states filterable by Generic business partner type
- [ ] Make business partner type in changelog entry non-nullable
