### ISSUE TITLE
Gate: Don't update Business Partners without change

### ISSUE THREAD

**Issue by nicoprow** [eclipse-tractusx/bpdm#573]
Currently, when business partner data for a given stage and external id should be upserted we should validate whether the business partner data really is different from the existing data in the database. Only when there is a change we should create change log entry. Likewise, only when business partner input is changed the Gate starts a golden record process.

### Tasks

- [x] Create validation logic comparing incoming business partner stage data with existing stage data
- [x] Only create changelog on changed data
- [x] Only create golden record tasks for changed data

**Comment by fabiodmota** [comment]
When an input is made, it should be validated if it already exists in the persistence to avoid always triggering the clean flow among all components.

**Key Point:**
What happens when a `taskId` from the Orchestrator is returned to the Gate and for some reason, the Orchestrator loses context? We won't have our data cleaned, but the persistence of the Input will remain the same as initially and won't trigger new requests that come in identically.

**Recommendation:**
Implementing a validation mechanism to check the input's existence in the persistence layer before proceeding could mitigate such issues and ensure the system handles new and identical requests efficiently.

**Comment by nicoprow** [comment]
> When an input is made, it should be validated if it already exists in the persistence to avoid always triggering the clean flow among all components.
> 
> **Key Point:** What happens when a `taskId` from the Orchestrator is returned to the Gate and for some reason, the Orchestrator loses context? We won't have our data cleaned, but the persistence of the Input will remain the same as initially and won't trigger new requests that come in identically.
> 
> **Recommendation:** Implementing a validation mechanism to check the input's existence in the persistence layer before proceeding could mitigate such issues and ensure the system handles new and identical requests efficiently.

The solution would be to the check the sharing state of the business partner whose data is being upserted. If the sharing state is in error a golden record task should be created regardless the input data is the same or not. If it is in Pending or in Success it should not be updated if the data is equal.
