### ISSUE TITLE
Refactor: Remove Opensearch component

### ISSUE THREAD

**Issue by nicoprow** [eclipse-tractusx/bpdm#577]
Since we now rely on the database directly to perform our name searches we should remove the opensearch component from the Pool.

### Tasks

- [ ] Remove opensearch classes from the BPDM Pool module
- [ ] Remove opensearch from the BPDM Pool tests
- [ ] Remove opensearch from the Bridge tests
- [ ] Remove opensearch from the Helm chart dependencies
