### ISSUE TITLE
Data Model: Split L/S/A Fields from Generic Business Partner

### ISSUE THREAD

**Issue by nicoprow** [eclipse-tractusx/bpdm#669]
The generic business partner has fields that belong definitely to a L/S/A typed business partner. For example legalForm, legalName or the BPN fields. According to the data model V5 we should split these L/S/A typed fields in to their own L/S/A subclasses (#631 ). This way the fields are better sorted and are more easily recognizable as belonging to a certain business partner type.

```mermaid
classDiagram

 class Business_Partner{
        External ID
        Name Parts
        Identifiers
        Roles
        Is Own Company Data
        Legal Entity
        Site
        Address
    }
    class LegalEntity{
        BPN
        Legal Name
        Short Name
        Legal Form
        Classifications
        Identifiers
        Confidence Criteria
    }

    class Site{
        BPN
        Name
        Confidence Criteria
    }

    class Address{
        BPN
        Address Type
        Name
        Identifiers
        States
        Confidence Criteria
        Physical Postal Address
        Alternative Postal Address
    }

Business_Partner --> LegalEntity: Can Have One
Business_Partner --> Site: Can Have One
Business_Partner --> Address: Can Have One

```

The changes will mainly affect the Gate model but also influence the model of the orchestrator which also relies on the generic business partner. The orchestrators model can be understood as an extension of the Gate's generic business partner in which the legal entity and site subclasses additionally have postal addresses  for the legal and site main address:

```mermaid
classDiagram

 class Business_Partner{
        External ID
        Name Parts
        Identifiers
        Roles
        Is Own Company Data
        Legal Entity
        Site
        Address
    }
    class LegalEntity{
        BPN
        Legal Name
        Short Name
        Legal Form
        Classifications
        Identifiers
        Confidence Criteria
        Legal Address
    }

    class Site{
        BPN
        Name
        Confidence Criteria
        Site Main Address
    }

    class Address{
        BPN
        Address Type
        Name
        Identifiers
        States
        Confidence Criteria
        Postal Address
    }

    class PostalAddress{
        Physical Postal Address
        Alternative Postal Address
    }

Business_Partner --> LegalEntity: Can Have One
Business_Partner --> Site: Can Have One
Business_Partner --> Address: Can Have One

LegalEntity --> PostalAddress: Can Have One
Site --> PostalAddress: Can Have One
Address --> PostalAddress: Can Have One

```

### Tasks

- [x] Separate L/S/A attributes for the Gate generic business partner
- [x] Separate L/S/A attributed for the Orchestrator generic business partner
- [x] Map new L/S/A attributes in cleaning service dummy
- [x] Map new L/S/A attributed in pool
- [x] Map new L/S/A attributed in Gate
- [x] Remove any structures in the generic data model to ensure backwards compatibility with the previous model

**Comment by nicoprow** [comment]
Currently the proposed models for Orchestrator and Gate look very similar and just differ by legal entity and site not having their address information in the Gate. I propose to add this address information to the Gate and align those models even further. This makes mapping easier and reduces complexity due to juggling many different model variations around.
