### ISSUE TITLE
Tests: Create Test Data Factory Methods

### ISSUE THREAD

**Issue by nicoprow** [eclipse-tractusx/bpdm#711]
Currently, we are relying on static object test data for our unit and integration tests. This results in a lot of duplicated code since we want to have sometimes several different test data. 

Instead it is a better approach to just create methods which create test data on demand just like demonstrated here: https://github.com/eclipse-tractusx/bpdm/blob/main/bpdm-pool/src/test/kotlin/org/eclipse/tractusx/bpdm/pool/service/TaskStepFetchAndReserveServiceTest.kt

The tests in this class use methods to create Orchestrator DTO test data on the fly. If we centralize such code for example in a common test module (#568) we could make our tests much simpler and quicker to adapt changes.

### Tasks

- [x] Pool Test Data Factory
- [ ] Gate Test Data Factory
- [x] Orchestrator Test Data Factory
