### ISSUE TITLE
deployment: change BPDM EDC 0.5 to EDC 0.6

### ISSUE THREAD

**Issue by HeyHardy** [eclipse-tractusx/bpdm#758]
Currently the BPDM EDC is deployed with version 0.5 and needs to be increased to 0.6.
this issues is for tracking the effort.
https://github.com/eclipse-tractusx/tractusx-edc/releases

### Tasks

- [x] upgrade EDC deployment 0.5 to 0.6
- [x] update EDC asset structure and cutting
- [x] configure EDC with all assets
- [x] update EDC setup documentation (includes postman)
- [x] update EDC test postman collection
