### ISSUE TITLE
Integration of GLEIF Codes in Meta Data Controller for BPDM Pool

### ISSUE THREAD

**Issue by HeyHardy** [eclipse-tractusx/bpdm#784]
As a sharing member, to align with global standards and enhance the interoperability of the Catena-X platform, I need to implement the [GLEIF Entity Legal Forms (ELF) codes](https://www.gleif.org/de/about-lei/code-lists/iso-20275-entity-legal-forms-code-list/) into the metadata controllers of both the Gate and Pool services. This integration is crucial for:

- [x] Standardization: Adopt ISO 20275 ELF codes for legal entity identification.
- [x] Enhanced Metadata: Include GLEIF codes in entity metadata for accurate legal form representation.
- [x] Improved Interoperability: Facilitate data exchange and verification across global platforms.
- [x] Data Quality: Support service providers in elevating data quality and reliability.
- [x] Testing: to ensure running E2E test
- [x] start with countries related the golive (inital load waves)

**Comment by nicoprow** [comment]
@HeyHardy Do we have some information about the license of this code list? We would need to reference the source together with the license if we want to integrate the list into our Pool.

**Comment by nicoprow** [comment]
As it was stated here https://www.gleif.org/en/about/open-data I will be taking the CC0-1.0 license for the data

**Comment by nicoprow** [comment]
> As a sharing member, to align with global standards and enhance the interoperability of the Catena-X platform, I need to implement the [GLEIF Entity Legal Forms (ELF) codes](https://www.gleif.org/de/about-lei/code-lists/iso-20275-entity-legal-forms-code-list/) into the metadata controllers of both the Gate and Pool services. This integration is crucial for:
> 
>     * [ ]  Standardization: Adopt ISO 20275 ELF codes for legal entity identification.
> 
>     * [ ]  Enhanced Metadata: Include GLEIF codes in entity metadata for accurate legal form representation.
> 
>     * [ ]  Improved Interoperability: Facilitate data exchange and verification across global platforms.
> 
>     * [ ]  Data Quality: Support service providers in elevating data quality and reliability.
> 
>     * [ ]  Testing: to ensure running E2E test
> 
>     * [ ]  start with countries related the golive (inital load waves)

@HeyHardy @Sebastian-Wurm 

The Gleif code list has a lot of columns and we need to make sure which information we want to overtake for the legal forms.

The legal forms model currently is quite simple and only has these fields:

1. Technical Key
2. Name
3. Abbreviation

My suggestion for mapping the information from the code list:

1. Technical Key -> "ELF Code"
2. Name -> "Entity Legal Form name Local name"
3. Abbreviation -> "Abbreviations Local language"

There is also transliterated versions for name and abbreviation available. 

What is your opinion?

**Comment by Sebastian-Wurm** [comment]
Let's discuss a proposal for a comprehensive solution being able to fulfill future UI input / filtering requirements. It should include:
- "ELF code" -> TechnicalKey (could be renamed to Code, but would be a breaking change)
- "Language Code (ISO 639-1)" -> Language **(new)**
- "Country Code (ISO 3166-1)" -> Country **(new)**
- "Country sub-division code (ISO 3166-2)" -> AdministrativeAreaLevel1 **(new)** 
- "Entity Legal Form name Local name" -> Name
- "Abbreviations Local language" -> Abbreviation (could be renamed to Abbreviation**s**, but would be a breaking change)
- "Entity Legal Form name Transliterated name (per ISO 01-140-10)" -> TransliteratedName **(new)**
- "Abbreviations transliterated" -> TransliteratedAbbreviation**s** **(new)**
- "ELF Status ACTV/INAC" -> State **(new, boolean)**

Note that in this proposal "TechnicalKey" and "Language" would be a compound key, as there are multiple entries for the same ELF code having different names and abbreviations for different languages, that are official languages in that country, e.g. for Canada it's English and French, for Finland it's Finnish and Swedish. 

Note that the ELF code can be issued either on country level or on the level 1 of the administrative areas. 

Note that the ELF code has multiple approved abbreviations, separated by a semicolon.

![image](https://github.com/eclipse-tractusx/bpdm/assets/114073985/2864d3b7-70a4-45b9-bac9-27168c2ffa1b)

**Comment by nicoprow** [comment]
Implemented in https://github.com/eclipse-tractusx/bpdm/pull/1064
